### ISSUE TITLE
Adding LICENSE

### ISSUE THREAD

**Issue by smiled0g** [mbejda/CoderGhostTheme#4]
Hi @mbejda,

This little theme is awesome for coders. One problem though: **it doesn't come with an opensource license**. I would really love to fork and modify this theme to suit my home language (Thai) and more than happy to attribute your name on the pages.

If that's not something you want, that's totally cool. Anyways, I appreciate your afford and hope you'd reply soon.

Thanks

**Comment by mbejda** [comment]
I intended for it to be open source. Have fun!

**Comment by smiled0g** [comment]
@mbejda I know :) Still, it would really help if you add a LICENSE file so that I know what kind of opensource license you intend to distribute the repository as. Github is very handy when it comes to adding a LICENSE file.

There are some differences among many opensource licenses. For example, an MIT license allows modification of source code without opensourcing it after the change, where as GPL is more strict, and require any derivative work to be distributed under GPL as well.

I would recommend MIT license as it's one of the most permissive and popular among hackers.

Cheers

**Comment by mbejda** [comment]
<img width="1078" alt="screen shot 2017-03-16 at 8 05 12 am" src="https://cloud.githubusercontent.com/assets/5429780/23995301/52ea0966-0a1f-11e7-97a4-9e4157772562.png">
License has been added.
