### ISSUE TITLE
When there is a  picture in the article I published,The picture is always too large to display properly，how can I fix it?

### ISSUE THREAD

**Issue by sionnx** [mbejda/CoderGhostTheme#5]
look here!
![image](https://user-images.githubusercontent.com/24622986/28318622-0760c9da-6bfe-11e7-957c-cde635a68367.png)

**Comment by mbejda** [comment]
I will push a fix for it ASAP.  What you can do is add CSS classes in the code injection section.
<img width="981" alt="screen shot 2017-07-19 at 8 22 33 am" src="https://user-images.githubusercontent.com/5429780/28366597-7d3d4964-6c5b-11e7-9d3f-df8869025087.png">
 
```
        img[src$="#full"] {
  
                border:1px solid #71859d;
    clear: both;
    width: 100% !important;
            margin-top:30px;
            margin-bottom:30px;
}
```

Then when you add an image source to the blog just prepend the `#full` anchor to the source.
