### ISSUE TITLE
Have the "home" link in post.hbs go to @blog.url

### ISSUE THREAD

**Issue by amh4r** [mbejda/CoderGhostTheme#7]
The "home" link in `post.hbs` points to `<a href="/">`, but it'd be better if it pointed to `<a href="{{@blog.url}}>`.

**Comment by rantanlan** [comment]
thanks, exactly what I just stumbled upon since my blog lives in a subdir...

**Comment by mbejda** [comment]
I agree 👍 
Will make those changes.

**Comment by mbejda** [comment]
Closing issue.
